spring.application.name=pracWeek1
server.port=9000
notification.type = email
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:file:C:/Users/Vinil S/Downloads/pracWeek1/pracWeek1/database/db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update